version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - "8500:8500"
  #    network_mode: host
  mysql:
    image: "mysql:latest"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379